# Generated by Django 3.2 on 2021-04-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='grade',
            field=models.IntegerField(choices=[(5, 'Grade 5'), (2, 'Grade 2'), (3, 'Grade 3'), (1, 'Grade 1'), (4, 'Grade 4')]),
        ),
        migrations.AlterField(
            model_name='leavemaster',
            name='grade',
            field=models.IntegerField(choices=[(5, 'Grade 5'), (2, 'Grade 2'), (3, 'Grade 3'), (1, 'Grade 1'), (4, 'Grade 4')]),
        ),
        migrations.AlterField(
            model_name='leavemaster',
            name='leave_type',
            field=models.CharField(choices=[('CL', 'Casual Leave'), ('LW', 'Leave Without Pay'), ('ML', 'Maternity Leave'), ('EL', 'Earned Leave'), ('SL', 'Sick Leave')], max_length=2),
        ),
    ]
